### ISSUE TITLE
Please improve docs re: graphql server objective (CRUD, parameters, dataloader/batch get) #28

### ISSUE THREAD

**Issue by bionicles** [Jonahss/ioredisgraph#9]
Hi, I want to use this for a GraphQL project but I'm unclear how do you specify the endpoint in docker compose ... and I get `ECONNREFUSED` when I use it like works with ioredis constructor;

Could you add a link to or list of the options for the RedisGraph constructor to the readme?

Also, to prevent query injections, it's critical to use parameters not string formatting. How do you do CRUD operations with ioredisgraph with query parameters?

How do you override the id in a CREATE query to use uuid or oauth2 user sub?

Another thought, how do you integrate this with Dataloader? We just need a function `keys => get(keys)` 

Thanks in advance, look forward to watch / use this project,
Bionicles

**Comment by bionicles** [comment]
https://node-postgres.com/features/queries here's an example of query parameters, used to prevent SQL injection in postgresql

**Comment by Jonahss** [comment]
Hi!

>how do you specify the endpoint in docker compose ... and I get ECONNREFUSED when I use it like works with ioredis constructor;

This module should work exactly like ioredis, just the first argument for the constructor is the graph name. After that, you put all the usual ioredis constructor arguments.
Unless you are passing an options object to the constructor, then you add `graphName` to the object.
Like this:
```
let graph = new RedisGraph('DEMO_GRAPH', 6379) // talks to a graph named 'DEMO_GRAPH' on port 6379 of localhost.

let graph = new RedisGraph({graphName: 'DEMO_GRAPH', port: 6379}) // equivalent to previous example, but using an options object.
```

For connecting to local docker instance, I use redisgraph's container:
`docker run -p 6379:6379 -it --rm redislabs/redisgraph`

------------------------------------------

>Could you add a link to or list of the options for the RedisGraph constructor to the readme?

ioredis has these docs for their constructor, so all this should work. Do you think I should add this link to the README here?
https://github.com/luin/ioredis/blob/master/API.md#new-redisport-host-options

---------------------------------------------

>Also, to prevent query injections, it's critical to use parameters not string formatting. How do you do CRUD operations with ioredisgraph with query parameters?

That's a good question!
You could find another module on npm for doing something like this. For example you'd do:
`graph.query("MATCH (r:Rider)-[:rides]->(t:Team) WHERE t.name = '${sanitize(userInput)}' RETURN r,t")`

A package like [validator](https://www.npmjs.com/package/validator) could work well for that.

We don't have a built-in way of sanitizing input, because this module doesn't do any query interpolation for you. There's no function where you pass a string and some variables. I'm just relying on you to make sure your string is clean before passing it in.

------------------------------------------

>How do you override the id in a CREATE query to use uuid or oauth2 user sub?

I'd ignore the redis ID and add your own id. Like `CREATE (:User {name:'Chuckwudi', oauth_id: '12345'})`

-----------------------------------------------------

I'm not familiar with Dataloader, but if you want to get all the nodes which match a set of id's, you could do it like this:
`graph.query("MATCH (t) WHERE id(t) IN [1,2,3] RETURN t")`

To use the `IN` query, you need to use a pre-release version, which can be gotten with:
```
docker pull redislabs/redisgraph:edge
docker run -p 6379:6379 -it --rm redislabs/redisgraph:edge
```
